/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop1;

import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SyedQadil
 */
public class f4 extends javax.swing.JFrame {

    /**
     * Creates new form f4
     */
    public f4() {
        initComponents();
          jPanel3.setVisible(false);
          
         // jp4.setVisible(false);
         // jp5.setVisible(false);
         // jp6.setVisible(false);
        
          jPanel5.setVisible(false);
          jPanel6.setVisible(false);
        // jPanel3.setBackground(new java.awt.Color(252, 16, 20,160));
        jPanel3.setBackground(new java.awt.Color(0, 102, 102,80));
          jPanel5.setBackground(new java.awt.Color(0, 102, 102,120));
            jPanel6.setBackground(new java.awt.Color(0, 102, 102,120));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jp9 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        jp3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jp4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        invtbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        sbc = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jp7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jp8 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jp10 = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jc3 = new javax.swing.JComboBox();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp9.setBackground(new java.awt.Color(102, 102, 102));

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Saled"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tbl1);

        javax.swing.GroupLayout jp9Layout = new javax.swing.GroupLayout(jp9);
        jp9.setLayout(jp9Layout);
        jp9Layout.setHorizontalGroup(
            jp9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jp9Layout.setVerticalGroup(
            jp9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel3.add(jp9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, 410, 270));

        jp3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amount");

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date");

        jTextField4.setText("Date");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setBackground(new java.awt.Color(0, 51, 204));
        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("Amount");

        javax.swing.GroupLayout jp3Layout = new javax.swing.GroupLayout(jp3);
        jp3.setLayout(jp3Layout);
        jp3Layout.setHorizontalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
            .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp3Layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(274, Short.MAX_VALUE)))
        );
        jp3Layout.setVerticalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp3Layout.createSequentialGroup()
                    .addGap(113, 113, 113)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(126, Short.MAX_VALUE)))
        );

        jPanel3.add(jp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jButton13.setFont(new java.awt.Font("Segoe UI Historic", 1, 11)); // NOI18N
        jButton13.setText("Daily");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 35, 82, -1));

        jButton18.setFont(new java.awt.Font("Segoe UI Historic", 1, 11)); // NOI18N
        jButton18.setText("Monthly");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 69, 82, -1));

        jButton19.setFont(new java.awt.Font("Segoe UI Historic", 1, 11)); // NOI18N
        jButton19.setText("Yearly");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 103, 82, -1));

        jButton20.setFont(new java.awt.Font("Segoe UI Historic", 1, 11)); // NOI18N
        jButton20.setText("Over-All");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 137, 82, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 570, 290));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp4.setBackground(new java.awt.Color(102, 102, 102));
        jp4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        invtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice", "Total", "Pay", "Balance", "Code", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(invtbl);

        jp4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 200));

        jPanel5.add(jp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 11, 450, 220));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Delete");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 80, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 51, 204));
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 60, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("delete by code");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 100, -1));

        jTextField13.setForeground(new java.awt.Color(0, 51, 204));
        jPanel5.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 82, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Search by Inv");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 210, 80, -1));

        jTextField14.setForeground(new java.awt.Color(0, 51, 204));
        jPanel5.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 60, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("delete by Date");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 80, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Search");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 80, -1));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Search by code");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 80, -1));

        sbc.setForeground(new java.awt.Color(0, 51, 204));
        sbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbcActionPerformed(evt);
            }
        });
        sbc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sbcKeyPressed(evt);
            }
        });
        jPanel5.add(sbc, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 82, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Search by Date");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 130, 80, -1));

        jTextField16.setForeground(new java.awt.Color(0, 0, 204));
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jTextField16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField16KeyPressed(evt);
            }
        });
        jPanel5.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 82, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 570, 290));

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp7.setBackground(new java.awt.Color(102, 102, 102));
        jp7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Email", "Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable4);

        jp7.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 190));

        jTextField2.setForeground(new java.awt.Color(0, 51, 204));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jp7.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Search");
        jp7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 43, 20));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jp7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 90, 20));

        jPanel6.add(jp7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 21, 400, 240));

        jButton25.setFont(new java.awt.Font("Segoe UI Historic", 1, 11)); // NOI18N
        jButton25.setText("Update");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 82, -1));

        jButton26.setFont(new java.awt.Font("Segoe UI Historic", 1, 11)); // NOI18N
        jButton26.setText("Add");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 82, -1));

        jp8.setBackground(new java.awt.Color(102, 102, 102));
        jp8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField3.setForeground(new java.awt.Color(0, 51, 153));
        jp8.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 80, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Balance");
        jp8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 80, 20));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jp8.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 80, -1));

        jTextField7.setForeground(new java.awt.Color(0, 51, 153));
        jp8.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 80, -1));

        jTextField8.setForeground(new java.awt.Color(0, 51, 153));
        jp8.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 80, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Name");
        jp8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 50, 50, 20));

        jLabel12.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Add People");
        jp8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 120, 30));

        jLabel22.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Email");
        jp8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 50, 50, 20));

        jPanel6.add(jp8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 21, 400, 240));

        jButton27.setFont(new java.awt.Font("Segoe UI Historic", 1, 11)); // NOI18N
        jButton27.setText("List");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 82, -1));

        jButton28.setFont(new java.awt.Font("Segoe UI Historic", 1, 11)); // NOI18N
        jButton28.setText("Delete");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 82, -1));

        jp10.setBackground(new java.awt.Color(102, 102, 102));
        jp10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField9.setForeground(new java.awt.Color(0, 51, 153));
        jp10.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 80, -1));

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Balance");
        jp10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 80, 20));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("Submit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jp10.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 80, -1));

        jTextField10.setForeground(new java.awt.Color(0, 51, 153));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField10KeyPressed(evt);
            }
        });
        jp10.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 80, -1));

        jTextField11.setForeground(new java.awt.Color(0, 51, 153));
        jp10.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 80, -1));

        jTextField12.setForeground(new java.awt.Color(0, 51, 153));
        jp10.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 80, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Search");
        jp10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 43, 20));

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Name");
        jp10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 50, 50, 20));

        jLabel16.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Email");
        jp10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 50, 50, 20));

        jLabel23.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("Edit People");
        jp10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 150, 30));

        jPanel6.add(jp10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 21, 400, 240));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 570, 290));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop1/The_Organizational_Puzzle_2-640x393.jpg"))); // NOI18N
        jLabel1.setText(" ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 630, 310));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jc3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jc3.setForeground(new java.awt.Color(0, 51, 51));
        jc3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sale", "Invoice", "Customer" }));
        jc3.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jc3ComponentAdded(evt);
            }
        });
        jc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc3jc1ActionPerformed(evt);
            }
        });
        jc3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jc3PropertyChange(evt);
            }
        });
        jPanel2.add(jc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        jButton15.setText("Home");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jButton16.setText("Sale");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jButton17.setText("Stock");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Record");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 150, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 630, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("RECORD PANEL");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 104, 130, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 130));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 630, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

         jp3.setVisible(true);
       jp9.setVisible(false);
       this.repaint();
        mdb ob=new mdb();
           jTextField4.setText("Date");
        jTextField5.setText("Amount");
        
        
      String dttt= JOptionPane.showInputDialog(null, "Enter Your desired date. Like , 09-11-2020");
        
        int i=ob.getsal(dttt);
        System.out.print(i);
        
        jTextField4.setText(dttt);
        jTextField5.setText(Integer.toString(i));
         this.repaint();
        
       
       
       

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed

   java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f3().setVisible(true);
            }
        });
   this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed


  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f1().setVisible(true);
            }
        });
   this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

   java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f6().setVisible(true);
            }
        });
   this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jc3ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jc3ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jc3ComponentAdded

    private void jc3jc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc3jc1ActionPerformed

       //String oo= jc3.getSelectedItem().toString();
       int ii=-1;  
        ii=jc3.getSelectedIndex();
         if (ii==0){ 
             
             jLabel8.setText("Sale Record");
          jPanel6.setVisible(false);
            jPanel5.setVisible(false);
           jPanel3 .setVisible(true);
           this.repaint();
         }
         
         if (ii==1){
          jLabel8.setText("Invoive Record");
          jPanel3.setVisible(false);
          jPanel6.setVisible(false);
          jPanel5 .setVisible(true);
          this.repaint();
         }
         
          if (ii==2){
          jLabel8.setText("Customer Record");
          jPanel3.setVisible(false);
          jPanel5.setVisible(false);
          jPanel6 .setVisible(true);
          jp10.setVisible(false);
          jp8.setVisible(false);
          jp7.setVisible(false);
          this.repaint();
          this.repaint();
                            }
         
    }//GEN-LAST:event_jc3jc1ActionPerformed

    private void jc3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jc3PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jc3PropertyChange

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed

        mdb ob=new mdb();
         jTextField4.setText("Month");
        jTextField5.setText("Amount");
         jp3.setVisible(true);
       jp9.setVisible(false);
        this.repaint();
        
      String dttt= JOptionPane.showInputDialog(null, "Enter Your desired month. Like ,01-2020");
        
        int i=ob.getsalm(dttt);
        System.out.print(i);
        
        jTextField4.setText(dttt);
        jTextField5.setText(Integer.toString(i));
        
        this.repaint();
 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
  
        this.repaint();
        jp3.setVisible(false); 
         jp9.setVisible(true);
         mdb ob=new mdb();
         ob.dailysale(tbl1);
         this.repaint();
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
 jp8.setVisible(true);
          jp7.setVisible(false);
            jp10.setVisible(false);
 
          this.repaint();
          
          mdb ob=new mdb();
          
          //ob.addcusto(jTextField7.getText(),jTextField8.getText(),Integer.parseInt(jTextField3.getText()));


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
  jp10.setVisible(true);
jp8.setVisible(false);
          jp7.setVisible(false);
          this.repaint();
      
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed

        jp10.setVisible(false);
jp8.setVisible(false);
          jp7.setVisible(true);
          this.repaint();
          
          mdb ob=new mdb();
          ob.showncusto(jTable4);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
String dttt= JOptionPane.showInputDialog(null, "Enter Customer Code");
int cd=Integer.parseInt(dttt);
mdb ob=new mdb();
ob.rmvcusto(cd);
 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    private void sbcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sbcKeyPressed
if(evt.getKeyCode()== KeyEvent.VK_ENTER)  
{ 
mdb ob=new mdb();
 
//int iop=Integer.parseInt(sbc.getText());
ob.invrcdc(0,sbc.getText(),invtbl);


}        // TODO add your handling code here:
    }//GEN-LAST:event_sbcKeyPressed

    private void sbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sbcActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyPressed
      if(evt.getKeyCode()== KeyEvent.VK_ENTER)  
{
mdb ob=new mdb();
int rt=Integer.parseInt(jTextField10.getText());
String st[]=new String[3];

st=ob.editg(rt); 
jTextField11.setText(st[0]);
jTextField12.setText(st[1]);
jTextField9.setText(st[2]);
this.repaint();

}  
     
    }//GEN-LAST:event_jTextField10KeyPressed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

mdb ob=new mdb();

int cd=Integer.parseInt(jTextField10.getText());
ob.updtcusto(cd,jTextField11.getText(),jTextField12.getText(),Integer.parseInt(jTextField9.getText()));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   mdb ob=new mdb();
   int bal=Integer.parseInt(jTextField3.getText());
ob.addcusto(jTextField7.getText(),jTextField8.getText(),bal);
 
   
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// DefaultTableModel mod= (DefaultTableModel) jTable4.getModel();
 ((DefaultTableModel)jTable4.getModel()).setNumRows(0);     
 
 
 mdb ob=new mdb();
 ob.showncusto(jTable4);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
   if(evt.getKeyCode()== KeyEvent.VK_ENTER)  
{  
     ((DefaultTableModel)jTable4.getModel()).setNumRows(0);
int cod=Integer.parseInt(jTextField2.getText());
mdb ob=new mdb();
 ob.sercusto(cod,jTable4);
}
// TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField16KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyPressed
       if(evt.getKeyCode()== KeyEvent.VK_ENTER)  
{  
     ((DefaultTableModel)jTable4.getModel()).setNumRows(0);
String dat=jTextField16.getText();

mdb ob=new mdb();

 ob.serinvbydat(dat,invtbl);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable invtbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JComboBox jc3;
    private javax.swing.JPanel jp10;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp4;
    private javax.swing.JPanel jp7;
    private javax.swing.JPanel jp8;
    private javax.swing.JPanel jp9;
    private javax.swing.JTextField sbc;
    private javax.swing.JTable tbl1;
    // End of variables declaration//GEN-END:variables
}
